version: "3.9"

services:
  proxy:
    build: .
    container_name: zero-trust-proxy
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - PORT=4000
    depends_on:
      - user-service
      - payment-service
      - db-service
    networks:
      - mesh

  user-service:
    build: ./services/user-service
    container_name: user-service
    ports:
      - "5001:5001"
    env_file:
      - .env
    environment:
      - PORT=5001
      - SERVICE_NAME=user-service
      - SERVICE_SECRET=${USER_SERVICE_SECRET}
      - USER_SERVICE_URL=http://user-service:5001
      - PAYMENT_SERVICE_URL=http://payment-service:5002
      - DB_SERVICE_URL=http://db-service:5003
      - PROXY_URL=http://zero-trust-proxy:4000
    networks:
      - mesh

  payment-service:
    build: ./services/payment-service
    container_name: payment-service
    ports:
      - "5002:5002"
    env_file:
      - .env
    environment:
      - PORT=5002
      - SERVICE_NAME=payment-service
      - SERVICE_SECRET=${PAYMENT_SERVICE_SECRET}
      - USER_SERVICE_URL=http://user-service:5001
      - PAYMENT_SERVICE_URL=http://payment-service:5002
      - DB_SERVICE_URL=http://db-service:5003
      - PROXY_URL=http://zero-trust-proxy:4000
    networks:
      - mesh

  db-service:
    build: ./services/db-service
    container_name: db-service
    ports:
      - "5003:5003"
    env_file:
      - .env
    environment:
      - PORT=5003
      - SERVICE_NAME=db-service
      - SERVICE_SECRET=${DB_SERVICE_SECRET}
      - USER_SERVICE_URL=http://user-service:5001
      - PAYMENT_SERVICE_URL=http://payment-service:5002
      - DB_SERVICE_URL=http://db-service:5003
      - PROXY_URL=http://zero-trust-proxy:4000
    networks:
      - mesh

networks:
  mesh:
    driver: bridge
